version: '2'

services:
  suggestions-api:
    # build: bothub-word-suggestion-api/Dockerfile
    image: suggestions-api:latest
    ports:
     - "5000:5000"
    restart:
      - always
  suggestions-webapp:
    # build: bothub-word-suggestion-webapp/Dockerfile
    image: suggestions-webapp:latest
    depends_on:
      - suggestions-api
    ports:
      - "4200:80"
    restart:
      - always